MDScreen:
    #md_bg_color:hex("#181f2b")

    MDTopAppBar:
        md_bg_color:hex("#181f6b")
        pos_hint:{"top":1}
        title:"Switch "
        left_action_items:[["arrow-left", lambda x:None]]
        elevation:3

    UITouchRipple:
        pos_hint:{"center_x":0.5, "center_y":0.5}
    UIButton:
        text:"Get Started"
        pos_hint:{"center_x":0.5, "center_y":0.1}






